# Generated by Django 2.1.3 on 2018-11-25 02:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('question_sentence', models.TextField()),
                ('question_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('question_choices', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=505, size=5)),
                ('question_answers', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='SelectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=50)),
                ('select_date', models.DateTimeField()),
                ('select_text', django_mysql.models.ListCharField(models.CharField(max_length=5), max_length=30, size=5)),
                ('latest_solve_state', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
