# Generated by Django 2.1.3 on 2018-11-26 08:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_selecthistory_q_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecthistory',
            name='latest_solve_state',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=55, size=5),
        ),
        migrations.AlterField(
            model_name='selecthistory',
            name='select_text',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=55, size=5),
        ),
    ]
