# Generated by Django 2.1.3 on 2018-12-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181126_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecthistory',
            name='select_status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
