# Generated by Django 2.1.3 on 2018-12-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_selecthistory_select_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_commentary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_series',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
