# Generated by Django 2.1.3 on 2018-12-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181201_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_sub',
            field=models.IntegerField(default=0),
        ),
    ]
