# Generated by Django 2.1.3 on 2018-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181201_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_series',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
